-- ============================================================
-- SPOOL BASE DE DATOS CONTROL DE GASTOS
-- Usuario recomendado: TALLERPRO1
-- Objetos actuales:
-- GANANCIAS
-- GASTOS
-- PRESUPUESTO_MES
-- V_INFORME_MENSUAL
-- V_RESUMEN_GANANCIAS
-- V_RESUMEN_GASTOS
-- ============================================================

SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
SET LONG 1000000
SET LONGCHUNKSIZE 1000000
SET LINESIZE 32767
SET TRIMSPOOL ON
SET VERIFY OFF

HOST mkdir C:\EXPORTS

EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SQLTERMINATOR',TRUE);
EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'PRETTY',TRUE);
EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_ATTRIBUTES',FALSE);
EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',FALSE);
EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'TABLESPACE',FALSE);

SPOOL C:\EXPORTS\BD_CONTROL_GASTOS.sql

PROMPT -- ============================================================
PROMPT -- SCRIPT GENERADO POR SPOOL - BASE DE DATOS CONTROL DE GASTOS
PROMPT -- ============================================================
PROMPT SET DEFINE OFF;
PROMPT SET SQLBLANKLINES ON;
PROMPT ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
PROMPT

PROMPT -- ============================================================
PROMPT -- ELIMINAR OBJETOS SI YA EXISTEN
PROMPT -- ============================================================

PROMPT BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_INFORME_MENSUAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
PROMPT /
PROMPT BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_RESUMEN_GANANCIAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
PROMPT /
PROMPT BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_RESUMEN_GASTOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
PROMPT /
PROMPT BEGIN EXECUTE IMMEDIATE 'DROP TABLE GANANCIAS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
PROMPT /
PROMPT BEGIN EXECUTE IMMEDIATE 'DROP TABLE GASTOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
PROMPT /
PROMPT BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRESUPUESTO_MES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
PROMPT /

PROMPT -- ============================================================
PROMPT -- ELIMINAR SECUENCIAS SI EXISTEN
PROMPT -- ============================================================

PROMPT BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GASTO'; EXCEPTION WHEN OTHERS THEN NULL; END;
PROMPT /
PROMPT BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GANANCIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
PROMPT /
PROMPT BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PRESUPUESTO_MES'; EXCEPTION WHEN OTHERS THEN NULL; END;
PROMPT /

PROMPT -- ============================================================
PROMPT -- CREACION DE TABLAS
PROMPT -- ============================================================

SELECT DBMS_METADATA.GET_DDL('TABLE','PRESUPUESTO_MES') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE','GASTOS') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE','GANANCIAS') FROM DUAL;

PROMPT -- ============================================================
PROMPT -- CREACION DE SECUENCIAS
PROMPT -- ============================================================

SELECT DBMS_METADATA.GET_DDL('SEQUENCE', SEQUENCE_NAME)
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN ('SEQ_GASTO','SEQ_GANANCIA','SEQ_PRESUPUESTO_MES')
ORDER BY SEQUENCE_NAME;

PROMPT -- ============================================================
PROMPT -- INSERTS TABLA PRESUPUESTO_MES
PROMPT -- ============================================================

SELECT
'INSERT INTO PRESUPUESTO_MES (ID_MES, ANIO, MES, SALDO_INICIAL) VALUES (' ||
ID_MES || ', ' ||
ANIO || ', ' ||
MES || ', ' ||
CASE
    WHEN SALDO_INICIAL IS NULL THEN 'NULL'
    ELSE TO_CHAR(SALDO_INICIAL, 'FM999999999999999990D999999', 'NLS_NUMERIC_CHARACTERS=.,')
END ||
');'
FROM PRESUPUESTO_MES
ORDER BY ID_MES;

PROMPT -- ============================================================
PROMPT -- INSERTS TABLA GASTOS
PROMPT -- ============================================================

SELECT
'INSERT INTO GASTOS (ID_GASTO, ID_MES, CATEGORIA, PREVISTO, REAL_GASTO) VALUES (' ||
ID_GASTO || ', ' ||
ID_MES || ', ' ||
CASE
    WHEN CATEGORIA IS NULL THEN 'NULL'
    ELSE '''' || REPLACE(CATEGORIA, '''', '''''') || ''''
END || ', ' ||
CASE
    WHEN PREVISTO IS NULL THEN 'NULL'
    ELSE TO_CHAR(PREVISTO, 'FM999999999999999990D999999', 'NLS_NUMERIC_CHARACTERS=.,')
END || ', ' ||
CASE
    WHEN REAL_GASTO IS NULL THEN 'NULL'
    ELSE TO_CHAR(REAL_GASTO, 'FM999999999999999990D999999', 'NLS_NUMERIC_CHARACTERS=.,')
END ||
');'
FROM GASTOS
ORDER BY ID_GASTO;

PROMPT -- ============================================================
PROMPT -- INSERTS TABLA GANANCIAS
PROMPT -- ============================================================

SELECT
'INSERT INTO GANANCIAS (ID_GANANCIA, ID_MES, CATEGORIA, PREVISTO, REAL_GANANCIA) VALUES (' ||
ID_GANANCIA || ', ' ||
ID_MES || ', ' ||
CASE
    WHEN CATEGORIA IS NULL THEN 'NULL'
    ELSE '''' || REPLACE(CATEGORIA, '''', '''''') || ''''
END || ', ' ||
CASE
    WHEN PREVISTO IS NULL THEN 'NULL'
    ELSE TO_CHAR(PREVISTO, 'FM999999999999999990D999999', 'NLS_NUMERIC_CHARACTERS=.,')
END || ', ' ||
CASE
    WHEN REAL_GANANCIA IS NULL THEN 'NULL'
    ELSE TO_CHAR(REAL_GANANCIA, 'FM999999999999999990D999999', 'NLS_NUMERIC_CHARACTERS=.,')
END ||
');'
FROM GANANCIAS
ORDER BY ID_GANANCIA;

PROMPT COMMIT;

PROMPT -- ============================================================
PROMPT -- CREACION DE VISTAS
PROMPT -- ============================================================

SELECT DBMS_METADATA.GET_DDL('VIEW','V_RESUMEN_GASTOS') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('VIEW','V_RESUMEN_GANANCIAS') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('VIEW','V_INFORME_MENSUAL') FROM DUAL;

PROMPT COMMIT;
PROMPT -- ============================================================
PROMPT -- FIN DEL SCRIPT
PROMPT -- ============================================================

SPOOL OFF

SET FEEDBACK ON
SET HEADING ON

PROMPT
PROMPT Archivo generado en:
PROMPT C:\EXPORTS\BD_CONTROL_GASTOS.sql
PROMPT